title: Chay's Blog
description: >-
  A blog on my reflections, experiments, and learnings.
domain: "itschebbal.in"
baseurl: ""
url: "https://itschebbal.in"
twitter_username: HebbalChaitanya
github_username: chebbal
share: true
social:
  type: Person
  links:
    - "https://twitter.com/HebbalChaitanya"
    - "https://linkedin.com/in/chaitanya-hebbal-21985339"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-seo-tag

# Theme settings
minimal_mistakes_skin: "dark"
search: true
locale: "en-US"

# Author
author:
  name: "Chaitanya B Hebbal"
  avatar: "/assets/images/avatar.png"
  bio: "Compilers · Robotics · AI"
  location: "Germany"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/chaitanya-hebbal-21985339/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/chebbal"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/HebbalChaitanya"

# Homepage header
header:
  overlay_color: "#000"
  overlay_filter: "0.5"
  title: "Chay's Blog"
  tagline: "Robotics · Edge AI · Ideas"

# Pagination
paginate: 5
paginate_path: /page:num/

# Include
include:
  - _pages

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: logs
    values:
      layout: single
      author_profile: false
      read_time: true
      share: false
      related: false

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
  logs:
    output: true
    permalink: /logs/:path/
  projects:
    output: false
    permalink: /projects/:path/

# Feed
atom_feed:
  hide: false

# Reading time
words_per_minute: 200

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/chebbal"

# Scripts
after_footer_scripts:
  - /assets/js/vendor/jquery/jquery-3.5.1.min.js